### ISSUE TITLE
OAS 3.0: Editing

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-editor#1376]
### Goal

Create an experience that supports the authoring of OAS 3.0 specs.

### Strategy

Most of the implementation should be contained in an OAS3 plugin. Depending on how complex the switching logic gets, hooks may need to be added into the existing core Editor plugins, in a similar manner to the hybrid core/plugin approach we ended up with in Swagger-UI's OAS3 rendering implementation.

With regard to the recent changes to the Autocomplete interface to make it more pluggable from the outside, we should take the high road here and make validation less opaque as well. It has benefits here and for end-users as well.

### Tasks

- [x] Swagger autocomplete engine
  - [x] Add switching logic for Swagger 2 / OAS 3
  - [x] Account for new specification constructs **10h/Med**
  - [x] Reorganize based on structural specification changes **15h/Med**
  - [x] Update $ref completer
- [x] Codegen interface
  - [x] Disable it for OAS until Codegen project catches up **2h/Low**
- [ ] JSONSchema validation
  - [x] Parse new OAS 3.0 JSONSchema **2h/Med**
  - [ ] Improve error messaging (new library? extended processing?) **4h/Low**
  - [ ] Migrate error transformers **8h/Medium**
- [ ] Semantic validation
  - [ ] Move to state-centered interface for validation **15h/Med**
  - [ ] Create validators for new OAS constructs **?**
  - [ ] Migrate validators for common constructs **10h/Med**

### Other notes

- Lockstep with UI: use the UI interface for detecting OAS specs whenever possible

**Comment by shockey** [comment]
cc @webron

**Comment by shockey** [comment]
### Autocomplete functionality checklist

- [ ] OpenAPI Object
- [ ] Info Object
- [ ] Contact Object
- [ ] License Object
- [ ] Server Object
- [ ] Server Variable Object
- [ ] Components Object
- [ ] Paths Object
- [ ] Path Item Object
- [ ] Operation Object
- [ ] External Documentation Object
- [ ] Parameter Object
- [ ] Request Body Object
- [ ] Media Type Object
- [ ] Encoding Object
- [ ] Responses Object
- [ ] Response Object
- [ ] Callback Object
- [ ] Example Object
- [ ] Link Object
- [ ] Header Object
- [ ] Tag Object
- [ ] Reference Object
- [ ] Schema Object
- [ ] XML Object
- [ ] Security Scheme Object
- [ ] OAuth Flows Object
- [ ] OAuth Flow Object
- [ ] Security Requirement Object
