### ISSUE TITLE
OAS 3.0: Semantic Validation

### ISSUE THREAD

**Issue by shockey** [swagger-api/swagger-editor#1460]
### TODO
- [x] $ref paths must start with a leading `/`
- [x] Operations that are either `GET` or `DELETE` cannot have `requestBody`
- [x] If there’s an ‘enum’ and a default value, the default value must be one from the enum values
- [x] You can’t have more than one parameter with a combination of name+in
- [x] A path definition _cannot_ contain query parameters in it (`/my/path?hello=world`)
- [ ] Headers are case-insensitive and should be checked within the same scope (parameters, responses...).
