### ISSUE TITLE
4.x release

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-editor#2710]
The goal of this issue is to update React to 17.x.y and have a remote branch on this repository running on React v17.x.y without any issues. More info in pre-release article: https://swagger.io/blog/api-design/what%E2%80%99s-ahead-for-swaggerui-v4-and-swaggereditor-v4/

## Current state

We're currently running Swagger-Editor on React@15.0.7 which was been released 8 months ago. React@15 release branch is more then 5 years old. It's time we start looking into what work would be required to make the update.

## Update methodology

We understand that merely updating React itself will not suffice. There is network of other libraries connected to React that need to update as well. We can use current test suite for detecting any anomalies after the React update. These anomalies needs to be documented first before we move for eliminating them. This issue will maintain a list of all anomalies that need to be eliminated along with the list of tasks that need to performed.

## Branch

All work in being done on [release/4.x](https://github.com/swagger-api/swagger-editor/tree/release/4.x) branch. [Draft PR](https://github.com/swagger-api/swagger-editor/pull/2711) has been opened as well from `release/4.x` branch.

## Community involvement

**Any community involvement is welcomed!** If you you're aware of any problem regarding usage of newer version of React then 15.0.7, please let us know in issue comments.

## Resources

- [React 16 release notes](https://reactjs.org/blog/2017/09/26/react-v16.0.html)
- [React 17 release notes](https://reactjs.org/blog/2020/10/20/react-v17.html)
- [enzyme 3.0.0 changelog](https://github.com/enzymejs/enzyme/blob/master/CHANGELOG.md#300) and [migration guide](https://github.com/enzymejs/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#migration-guide-for-enzyme-v2x-to-v3x)

## Tasks

- [x] [Update React to 17.x.y](#user-content-update-react-to-17-x-y)
- [x] [Detect and update all React related dependencies that will require update too](#user-content-detect-and-update-all-react-related-dependencies)
- [x] Detect and document all anomalies
- [x] Fix all anomalies
- [x] merge all pending dependabots PRs and rebase to v4
- [x] fix npm security vulnerabilities (fixed 144 of 155)
- [x] use SwaggerUI@v4 as dependency 
- [x] prefix lifecycle methods with `UNSAFE_` (31aa60515e3e38f085c92de3c4511a7584f0b3da)
- [x] We don't want to v4 (pre-release) land in [editor.swagger.io](https://editor.swagger.io/)
- [x] resolve all security vulnerabilities (dismiss rest)
- [x] update husky to v7 and delete huskyrc file
- [x]  bugs/1862.js failing test (416499e6fd52f19a0dd261dfbf3c968a09a10d44)

### Update React to 17.x.y <a href="#user-content-update-react-to-17-x-y" id="update-react-to-17-x-y">#</a>

react and react-dom packages have been updated to v17.0.2. Console did not reported any problem. Tests immediately stopped passing.

| Updated | Name        | Used version           | Latest version |
| -----:| ------------- |:-------------:| -----:|
| &check; | [react](https://www.npmjs.com/package/react) | [15.7.0](https://www.npmjs.com/package/react/v/15.7.0) | [17.0.2](https://www.npmjs.com/package/react/v/17.0.2) |
| &check; | [react-dom](https://www.npmjs.com/package/react-dom) | [15.7.0](https://www.npmjs.com/package/react-dom/v/15.7.0) | [17.0.2](https://www.npmjs.com/package/react-dom/v/17.0.2) |

### Detect and update all React related dependencies that will require update too <a href="#user-content-detect-and-update-all-react-related-dependencies" id="detect-and-update-all-react-related-dependencies">#</a>

**Production Dependencies**

| Updated | Name        | Used version           | Latest version |
| -----:| ------------- |:-------------:| -----:|
| &check; | [react-redux](https://www.npmjs.com/package/react-redux) | [4.4.10](https://www.npmjs.com/package/react-redux/v/4.4.10) | [7.2.4](https://www.npmjs.com/package/react-redux/v/7.2.4) |
| &check; | [redux](https://www.npmjs.com/package/redux) | [3.7.2](https://www.npmjs.com/package/redux/v/3.7.2) | [4.1.0](https://www.npmjs.com/package/redux/v/4.1.0) |

**Development Dependencies**

| Updated | Name        | Used version           | Latest version |
| -----:| ------------- |:-------------:| -----:|
| &check; | [react-test-renderer](https://www.npmjs.com/package/react-test-renderer) | [15.6.2](https://www.npmjs.com/package/react-test-renderer/v/15.6.2) | [17.0.2](https://www.npmjs.com/package/react-test-renderer/v/17.0.2) | 

## Anomalies

- [x] [`test-in-node` npm script fails](#user-content-test-in-node-npm-script-fails)
- [x] [`test:unit-jest` npm script fails](#user-content-test-unit-jest-npm-script-fails)
- [x] [`requestSnippets` error](#user-content-request-snippets-error)
- [x] [editor suggestions plugins throw error when being merge into SwaggerUI system](#user-content-editor-suggestions-plugins)
- [x] node@16 GA not running; fixed in 16eddf4db2c975731eb364dc923694e6b263750b
- [x] [Each child in a list should have a unique "key" prop in browser console](#user-content-unique-key-prop)
- [x] bug detected in https://github.com/swagger-api/swagger-editor/issues/2761 
### `test-in-node` npm script fails <a href="#user-content-test-in-node-npm-script-fails" id="test-in-node-npm-script-fails">#</a>

`test-in-node` npm script triggers errors. Current version of enzyme doesn't support react@17. In order for enzyme to work with react@17 we need to update enzyme to latest version and use [@wojtekmaj/enzyme-adapter-react-17](https://github.com/wojtekmaj/enzyme-adapter-react-17) adapter. Fixed in 489434025cd9148cee429d3f0c6421a16358fcb3.

### `test:unit-jest` npm script fails <a href="#user-content-test-unit-jest-npm-script-fails" id="test-unit-jest-npm-script-fails">#</a>

There seems to be some kind of recursive problem in Jest tests. Problem is in `test/unit/plugins/editor-metadata/index.js` file and `test/unit/plugins/validate-semantic/` directory. Reason for  script to fail is the [`requestSnippets` error](#user-content-request-snippets-error). This errors forces Jest to print entire dist bundle source code before the tests are considered as `passed`. Fixed in 37b7530c9dc18407c3fa1fe4e52b8124c03946ef.

### `requestSnippets` error  <a href="#user-content-request-snippets-error" id="request-snippets-error">#</a>

When running tests `redux` outputs (using `console.error`) following error:

```
  console.error
    Unexpected property "requestSnippets" found in previous state received by the reducer. Expected to find one of the known reducer property names instead: "spec", "err", "configs". Unexpected properties will be ignored.
```
The reason why we see this is that `redux` expects root reducers to return object with the same shape and initial state.

More about this problem here: 
 - https://stackoverflow.com/questions/33677833/react-redux-combining-reducers-unexpected-keys
 - https://stackoverflow.com/questions/41826224/warning-unexpected-key-a-found-in-previous-state-received-by-the-reducer/52290991

Fixed in 37b7530c9dc18407c3fa1fe4e52b8124c03946ef.

### editor suggestions plugins throw error when being merge into SwaggerUI system <a href="#user-content-editor-suggestions-plugins" id="editor-suggestions-plugins">#</a>

The mergin of editor suggestions plugins failed because of the way they were imported and used. Doing import in following fashion `import * as symbol from 'module'` is fine, but using the `symbol` further as an object is not fine. `symbol` will become special object with special properties and merging on it using lodash.merge will not work as it defines only getters and not setters. Fixed in https://github.com/swagger-api/swagger-editor/pull/2711/commits/85e2e3a19e5082d0ef2a8df7ac6063b6762c61f9

### Each child in a list should have a unique "key" prop in browser console <a href="#user-content-unique-key-prop" id="unique-key-prop">#</a> 

![image](https://user-images.githubusercontent.com/193286/129161764-651381a9-0423-4f42-8ba3-24123070091d.png)

Fixed in a532b443cf13de5f566ddcfae68a8c51a772fafd

**Comment by char0n** [comment]
`.github/dependabot.yaml` has been renamed to `.github/_dependabot_.yaml`; needs to be renamed after going for v4 stable.

**Comment by tim-lai** [comment]
@char0n I suggest adding 1 task item:

- replace componentWillReceiveProps with UNSAFE_componentWillReceiveProps (1 instance)

reference [here](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html)

**Comment by char0n** [comment]
Released as swagger-editor@4.0.0
