### ISSUE TITLE
Migrate build system to webpack 5

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-editor#2944]
**TODO:**: 

- [ ] test CRA behavior
 - [x] verify docker build after merge
 - [x] process https://github.com/swagger-api/swagger-editor/issues/2146

 ### Content & configuration

n/a

### Is your feature request related to a problem?

Update dependencies and security fixes.

### Describe the solution you'd like

Match SwaggerUI [PR#7826](https://github.com/swagger-api/swagger-ui/pull/7826) to Webpack@5 and WebpackDevServer@4 i

**Comment by char0n** [comment]
We're seeing following source map problems with SwaggerEditor build fragments build using new webpack@5 build system. Although there are many **WARNINGS**, SwaggerEditor successfully builds with CRA@5 using following code:

```js
import SwaggerEditor from 'swagger-editor';
import 'swagger-editor/dist/swagger-editor.css';

import reportWebVitals from './reportWebVitals';

SwaggerEditor({
  dom_id: '#root',
  // layout: 'StandaloneLayout',
});

// If you want to start measuring performance in your app, pass a function
// to log results (for example: reportWebVitals(console.log))
// or send to an analytics endpoint. Learn more: https://bit.ly/CRA-vitals
reportWebVitals();
```

**Build warnings**:

```
Failed to parse source map: 'webpack://swagger-editor/./node_modules/react-syntax-highlighter/dist/esm/styles/hljs/tomorrow-night.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/react/cjs/react.production.min.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/react/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/redux-immutable/dist/combineReducers.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/redux-immutable/dist/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/redux-immutable/dist/utilities/getStateName.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/redux-immutable/dist/utilities/getUnexpectedInvocationParameterMessage.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/redux-immutable/dist/utilities/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/redux-immutable/dist/utilities/validateNextState.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/redux/es/redux.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/regenerator-runtime/runtime.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/remarkable/dist/esm/index.browser.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/remarkable/dist/esm/linkify.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/repeat-string/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/requires-port/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/reselect/es/defaultMemoize.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/reselect/es/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/scheduler/cjs/scheduler.production.min.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/scheduler/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/serialize-error/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/side-channel/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/superagent/lib/agent-base.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/superagent/lib/client.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/superagent/lib/is-object.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/superagent/lib/request-base.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/superagent/lib/response-base.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/superagent/lib/utils.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/constants.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/execute/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/execute/oas3/build-request.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/execute/oas3/content-serializer.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/execute/oas3/parameter-builders.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/execute/oas3/style-serializer.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/execute/swagger2/build-request.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/execute/swagger2/parameter-builders.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/helpers.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/http/fold-formdata-to-request.browser.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/http/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/resolver.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/helpers.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/lib/all-of.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/lib/context-tree.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/lib/create-error.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/lib/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/lib/parameters.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/lib/properties.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/specmap/lib/refs.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/es/subtree-resolver/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/node_modules/is-plain-object/dist/is-plain-object.mjs' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/node_modules/qs/lib/formats.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/node_modules/qs/lib/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/node_modules/qs/lib/parse.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/node_modules/qs/lib/stringify.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-client/node_modules/qs/lib/utils.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-ui/dist/swagger-ui-es-bundle-core.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-ui/node_modules/randexp/lib/randexp.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-ui/node_modules/ret/lib/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-ui/node_modules/ret/lib/positions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-ui/node_modules/ret/lib/sets.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-ui/node_modules/ret/lib/types.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/swagger-ui/node_modules/ret/lib/util.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/toggle-selection/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/traverse/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/tslib/tslib.es6.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/uri-js/dist/es5/uri.all.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/url-parse/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/url/node_modules/punycode/punycode.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/url/url.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/url/util.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/util/node_modules/inherits/inherits_browser.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/util/support/isBufferBrowser.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/util/util.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/worker-loader/dist/runtime/inline.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/xml-but-prettier/dist/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/composer.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/constructor.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/dumper.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/emitter.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/errors.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/events.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/loader.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/nodes.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/parser.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/reader.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/representer.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/resolver.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/scanner.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/serializer.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/tokens.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/util.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/yaml-js/lib/yaml.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./node_modules/zenscroll/zenscroll.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/layout.jsx' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/ast/ast.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/ast/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-keywords/get-completions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-keywords/get-keywords-for-path.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-keywords/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-keywords/keyword-map.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-keywords/wrap-actions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-oas3-keywords/get-completions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-oas3-keywords/get-keywords-for-path.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-oas3-keywords/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-oas3-keywords/keyword-map.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-oas3-keywords/oas3-objects.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-oas3-keywords/wrap-actions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-refs/get-completions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-refs/get-refs-for-path.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-refs/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-refs/wrap-actions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-snippets/get-completions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-snippets/get-snippets-for-path.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-snippets/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-snippets/snippets.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest-snippets/wrap-actions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest/actions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest/fn.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest/helpers.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor-autosuggest/spec-selectors.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/actions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/components/brace-snippets-yaml.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/components/editor-container.jsx' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/components/editor.jsx' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/editor-helpers/marker-placer.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/editor-plugins/gutter-click.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/editor-plugins/hook.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/editor-plugins/json-to-yaml.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/editor-plugins/tab-handler.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/reducers.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/selectors.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/editor/spec.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/json-schema-validator/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/json-schema-validator/validator.worker.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/jump-to-path/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/jump-to-path/jump-to-path.jsx' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/jump-to-path/spec.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/local-storage/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/local-storage/petstore.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/performance/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/refs-util.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/split-pane-mode/components/split-pane-mode.jsx' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/split-pane-mode/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-base/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/actions.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/helpers.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/index.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/selectors.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/form-data.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/helpers.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/oas3/components.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/oas3/operations.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/oas3/parameters.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/oas3/refs.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/oas3/schemas.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/parameters.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/paths.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/schema.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/security.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/2and3/operations.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/2and3/parameters.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/2and3/paths.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/2and3/refs.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/2and3/schemas.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/2and3/security.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/plugins/validate-semantic/validators/2and3/tags.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/./src/window.js' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/bootstrap' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/amd define' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/compat get default export' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/create fake namespace object' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/define property getters' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/global' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/hasOwnProperty shorthand' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/make namespace object' URL is not supported

Failed to parse source map: 'webpack://swagger-editor/webpack/runtime/node module decorator' URL is not supported

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/array/from.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/array/is-array.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/date/now.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/bind.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/concat.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/ends-with.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/entries.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/every.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/fill.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/filter.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/find-index.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/find.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/flat-map.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/for-each.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/includes.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/index-of.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/keys.js' URL is not supported

WARNING in ./node_modules/swagger-editor/dist/swagger-editor-es-bundle.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://swagger-editor/./node_modules/@babel/runtime-corejs3/core-js-stable/instance/last-index-of.js' URL is not supported
```
