### ISSUE TITLE
Enable CodeQL and solve all the issues it finds

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-editor#5040]
**TODO**:

- [x] enable advanced CodeQL SAST on `master` branch
- [x] eliminate all false positives
- [x] remedy or mitigate all positives (remediation is preferred)
