### ISSUE TITLE
SwaggerEditor@next: enable CodeQL and solve all the issues it finds

### ISSUE THREAD

**Issue by char0n** [swagger-api/swagger-editor#5041]
**TODO**:

- [x] enable advanced CodeQL SAST on `next` branch
- [x] eliminate all false positives
- [x] remedy or mitigate all positives (remediation is preferred)

**Comment by char0n** [comment]
No issues founds.
